---

- name: Install guacd dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ PACKAGES.guacd }}"

- name: Install libvncserver
  package:
    name: "{{ PACKAGES.vnc_lib }}"
    state: present

- name: Copy guacd source
  copy:
    src: files/guacamole-server-0.9.10-incubating.tar.gz
    dest: /tmp

- name: Extract the guacd source
  unarchive:
    src: /tmp/guacamole-server-0.9.10-incubating.tar.gz
    copy: no
    dest: /tmp
    creates: /tmp/guacamole-server-0.9.10-incubating

- name: Build guacamole-server from source
  command: "{{ item }}"
  args:
    chdir: /tmp/guacamole-server-0.9.10-incubating
    creates: /usr/local/sbin/guacd
  with_items: [ ./configure --with-init-dir=/etc/init.d, make, make install ]
  register: guacd_build

- name: Run ldconfig if guacd was freshly installed
  command: ldconfig
  when: guacd_build.changed == true

- tags: guacd_ssl
  block:
    - name: Create SSL certs directory
      file:
        path: /etc/private
        state: directory
        mode: 0700

    - name: Create self-signed SSL cert and key
      command: >
        openssl req -new -nodes -x509 -subj "/C=US" -days 365 -newkey rsa:4096 -keyout key.pem -out cert.pem
      args:
        chdir: /etc/private
        creates: /etc/private/key.pem

    - name: Change permissions of SSL files
      file:
        path: "/etc/private/{{ item }}"
        mode: 0600
      with_items: [ 'cert.pem', 'key.pem' ]
  when: guacd_ssl == true
