---

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Install pre-dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ PACKAGES.prep }}"
  tags: prepare

- name: Include guacd tasks
  include: guacd.yml
  tags: guacd

- name: Include web_client tasks
  include: web_client.yml
  tags: web_client

- tags: ufw
  block:
    - name: Open ports
      ufw:
        rule: allow
        port: "{{ item }}"
        state: enabled
      with_items:
        - "{{ nginx_port }}"
        - "{{ nginx_https_port }}"
        - "{{ ssh_port }}"

    - name: Close Tomcat7 port
      ufw:
        rule: deny
        port: "{{ tomcat_port }}"
  when: ansible_distribution == "Ubuntu"

- name: Cleanup temp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/guacamole-server.tar.gz
    - /tmp/guacamole-server-0.9.10-incubating
  ignore_errors: yes
  tags: cleanup

- name: restart services (tomcat,guacd,nginx,ufw)
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items: [ tomcat7, guacd, nginx, ufw ]
  ignore_errors: yes
  tags: restart
  changed_when: False
