---

- name: Open UFW ports
  ufw:
    rule: allow
    port: "{{ item }}"
    state: enabled
  with_items:
    - "{{ nginx_port }}"
    - "{{ nginx_https_port }}"
    - "{{ ssh_port }}"

- name: Prepare config directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ CONFIG_DIR }}"
    - "{{ NGINX_DIR }}"
    - "{{ GUACAMOLE_DIR }}"
    - "{{ key_directory }}"
    - "{{ GUACAMOLE_DIR }}/extensions"

- name: Fill out Nginx template
  template:
    src: "nginx-guacamole.conf.j2"
    dest: "{{ NGINX_DIR }}/nginx-guacamole.conf"

- name: Fill out guacamole.properties template
  template:
    src: "guacamole.properties"
    dest: "{{ GUACAMOLE_DIR }}/guacamole.properties"

- name: Download theme file to extensions directory
  get_url:
    url: "https://github.com/cyverse/guac-cyverse-theme/releases/download/{{ install_type }}-theme/{{ install_type }}-theme.jar"
    dest: "{{ GUACAMOLE_DIR }}/extensions/{{ install_type }}-theme.jar"

- name: Download authentication plugin
  get_url:
    url: "https://github.com/cyverse/guacamole-auth-hmac/releases/download/{{ guacamole_version }}/guacamole-auth-hmac-{{ guacamole_version }}.jar"
    dest: "{{ GUACAMOLE_DIR }}/extensions/guacamole-auth-hmac-{{ guacamole_version }}.jar"

- name: Fill out docker-compose template
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ CONFIG_DIR }}/docker-compose.yml"

- name: Get certbot auto
  get_url:
    dest: /tmp
    url: https://dl.eff.org/certbot-auto
    mode: a+x

- name: Use certbot-auto with no email
  command: >
    /tmp/certbot-auto certonly --standalone -n --agree-tos --register-unsafely-without-email -d {{ ansible_fqdn }}
