---

- name: Gather OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: vars

- name: Install pre-dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ PACKAGES.prep }}"
  tags: prepare

- name: Include guacd tasks
  include: guacd.yml
  tags: guacd

- name: Include web_client tasks
  include: web_client.yml
  tags: web_client

- tags: hmac
  block:
    - name: Download guacamole-auth-hmac source
      git:
        clone: yes
        dest: /tmp/guacamole-auth-hmac
        repo: https://github.com/calvinmclean/guacamole-auth-hmac.git
        force: yes

    - name: Build the jar
      command: mvn package
      args:
        chdir: /tmp/guacamole-auth-hmac
        creates: /tmp/guacamole-auth-hmac/target/guacamole-auth-hmac-0.9.10-incubating.jar

    - name: Move hmac.jar to extensions directory
      copy:
        src: /tmp/guacamole-auth-hmac/target/guacamole-auth-hmac-0.9.10-incubating.jar
        dest: "{{ GUACAMOLE_HOME }}/extensions/guacamole-auth-hmac-0.9.10-incubating.jar"
        remote_src: yes

- tags: ufw
  block:
  - name: Open ports
    ufw:
      rule: allow
      port: "{{ item }}"
      state: enabled
    with_items:
      - "{{ nginx_port }}"
      - "{{ nginx_https_port }}"
      - "{{ ssh_port }}"

  - name: Close Tomcat7 port
    ufw:
      rule: deny
      port: "{{ tomcat_port }}"

- name: Cleanup temp files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/guacamole-server.tar.gz
    - /tmp/guacamole-server-0.9.10-incubating
    - /tmp/guacamole-auth-hmac
  ignore_errors: yes
  tags: cleanup

- name: restart services (tomcat,guacd,nginx,ufw)
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items: [ tomcat7, guacd, nginx, ufw ]
  ignore_errors: yes
  tags: restart
  changed_when: False
