---

- name: Install web client dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ PACKAGES.web_client }}"

- name: Copy web_client war
  copy:
    src: files/guacamole-0.9.10-incubating.war
    dest: /var/lib/tomcat7/webapps/guacamole.war

- name: Make GUACAMOLE_HOME directory
  file:
    path: "{{ GUACAMOLE_HOME }}"
    state: directory

- name: Symbolically link GUACAMOLE_HOME to /etc/guacamole
  file:
    src: "{{ GUACAMOLE_HOME }}"
    dest: /etc/guacamole
    state: link

- name: Add guacd.conf w/ SSL paths to GUACAMOLE_HOME
  template:
    src: guacd.conf.j2
    dest: "{{ GUACAMOLE_HOME }}/guacd.conf"
  when: guacd_ssl == true

- name: Make GUACAMOLE_HOME/extensions directory
  file:
    path: "{{ GUACAMOLE_HOME }}/extensions"
    state: directory

- name: Add CyVerse theme to Guacamole
  copy:
    src: files/cyverse-theme.jar
    dest: "{{ GUACAMOLE_HOME }}/extensions"

- name: Move HMAC authentication jar to extensions directory
  copy:
    src: files/hmac-0.9.10-incubating.jar
    dest: "{{ GUACAMOLE_HOME }}/extensions"
  tags: hmac

- name: Add guacamole.properties to "{{ GUACAMOLE_HOME }}"
  template:
    src: guacamole.properties.j2
    dest: "{{ GUACAMOLE_HOME }}/guacamole.properties"

- name: Restart Tomcat7 so its files are accessible
  service:
    name: tomcat7
    state: restarted
  changed_when: False


- tags: reverse_proxy
  block:
    - name: Get certbot auto
      get_url:
        dest: /tmp
        url: https://dl.eff.org/certbot-auto
        mode: a+x

    - name: Use certbot-auto
      command: >
        /tmp/certbot-auto certonly --standalone -n --agree-tos --register-unsafely-without-email -d {{ ansible_fqdn }}

    - name: Add nginx reverse proxy config to sites-available
      template:
        src: nginx-guacamole.j2
        dest: /etc/nginx/sites-available/nginx-guacamole

    - name: Create symbolic link for nginx config to sites-enabled
      file:
        src: /etc/nginx/sites-available/nginx-guacamole
        dest: /etc/nginx/sites-enabled/nginx-guacamole
        state: link

    - name: Remove sites-enabled and sites-available 'default' conf
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/nginx/sites-available/default
        - /etc/nginx/sites-enabled/default

- tags: tomcat
  block:
    - name: Add CorsFilter to Tomcat7
      template:
        src: web.xml.j2
        dest: /var/lib/tomcat7/webapps/guacamole/WEB-INF/web.xml
        force: yes

    - name: Set Tomcat7 port
      lineinfile:
        dest: /var/lib/tomcat7/conf/server.xml
        state: present
        regexp: <Connector port="8080" protocol="HTTP/1.1"
        line: '    <Connector port="{{ tomcat_port }}" protocol="HTTP/1.1"'
